version: '3'

services:
  app:
    build:
      context: .
      args:
        CODE_ROOT: src
    image: base-vuejs:3
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - logs:/var/log/artifakt

volumes:
  logs:
